//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScreenStateApi.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class socketlib_serverEntities : DbContext
    {
        public socketlib_serverEntities()
            : base("name=socketlib_serverEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TH_HARDWARE_STATE> TH_HARDWARE_STATE { get; set; }
        public virtual DbSet<TS_SOCKETLIB_CONFIG> TS_SOCKETLIB_CONFIG { get; set; }
    }
}
