//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScreenStateApi.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TH_HARDWARE_STATE
    {
        public string recordid { get; set; }
        public string hardsn { get; set; }
        public string computername { get; set; }
        public string errornum { get; set; }
        public Nullable<System.DateTime> producetime { get; set; }
        public Nullable<System.DateTime> uploadtime { get; set; }
        public Nullable<System.DateTime> storetime { get; set; }
        public string savetype { get; set; }
    }
}
