//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScreenStateApi.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TS_SOCKETLIB_CONFIG
    {
        public int id { get; set; }
        public string hardsn { get; set; }
        public string computername { get; set; }
        public string nodecomputername { get; set; }
        public string cityname { get; set; }
        public string linename { get; set; }
        public string stationname { get; set; }
        public string terminaltype { get; set; }
        public int clienttype { get; set; }
        public Nullable<int> stationseq { get; set; }
        public string projectname { get; set; }
        public Nullable<System.DateTime> modifytime { get; set; }
        public string modifier { get; set; }
        public string verifier { get; set; }
        public string usedmark { get; set; }
        public string citycode { get; set; }
        public string position { get; set; }
        public string screentype { get; set; }
    }
}
